/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author pedrojgl
 */
public class NamesCapture extends javax.swing.JDialog {
    private final static int MAX = 4;
    private int nplayers;
    private ArrayList<String> names;
    private ArrayList<javax.swing.JTextField> names_fields;
    private ArrayList<javax.swing.JLabel> names_labels;
    /**
     * Creates new form NamesCapture
     */
    public NamesCapture(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public NamesCapture(javax.swing.JFrame parent) {
        super(parent, true);   // El parámetro  true  indica que la aplicación se quedará esperando
        //a que se cierre el cuadro de diálogo
        // Se inicializa el atributo que alojará los nombres escritos por el usuario
        names = new ArrayList<>();
        nplayers = 1;
        names_fields = new ArrayList<>();
        names_labels = new ArrayList<>();
        
        initComponents();
        
        names_fields.add(n1_cuadrotxt);
        names_fields.add(n2_cuadrotxt);
        names_fields.add(n3_cuadrotxt);
        names_fields.add(n4_cuadrotxt);
        names_labels.add(NOMBRE1_label);
        names_labels.add(NOMBRE2_label);
        names_labels.add(NOMBRE3_label);
        names_labels.add(NOMBRE4_label);
        
        for (int i = 0; i < MAX; i++){
            if (i == 0){
                names_fields.get(i).setVisible(true);
                names_labels.get(i).setVisible(true);
            } else{
                names_fields.get(i).setVisible(false);
                names_labels.get(i).setVisible(false);
            }
        }
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Aquí se programa lo que se desea hacer si el usuario cierra la ventana.
            }
        });
    }
    
    public ArrayList<String> getNames(){
        this.setVisible (true);
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        anidir_boton = new javax.swing.JButton();
        eliminar_boton = new javax.swing.JButton();
        n1_cuadrotxt = new javax.swing.JTextField();
        NOMBRE1_label = new javax.swing.JLabel();
        aceptar_boton = new javax.swing.JButton();
        NOMBRE2_label = new javax.swing.JLabel();
        n2_cuadrotxt = new javax.swing.JTextField();
        NOMBRE3_label = new javax.swing.JLabel();
        n3_cuadrotxt = new javax.swing.JTextField();
        NOMBRE4_label = new javax.swing.JLabel();
        n4_cuadrotxt = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        anidir_boton.setText("+");
        anidir_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anidir_botonActionPerformed(evt);
            }
        });

        eliminar_boton.setText("-");
        eliminar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_botonActionPerformed(evt);
            }
        });

        n1_cuadrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_cuadrotxtActionPerformed(evt);
            }
        });

        NOMBRE1_label.setText("Nombre 1:");

        aceptar_boton.setText("Aceptar");
        aceptar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_botonActionPerformed(evt);
            }
        });

        NOMBRE2_label.setText("Nombre 2:");

        n2_cuadrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2_cuadrotxtActionPerformed(evt);
            }
        });

        NOMBRE3_label.setText("Nombre 3:");

        n3_cuadrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3_cuadrotxtActionPerformed(evt);
            }
        });

        NOMBRE4_label.setText("Nombre 4:");

        n4_cuadrotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4_cuadrotxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anidir_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NOMBRE4_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(n4_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NOMBRE2_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(n2_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NOMBRE1_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(n1_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NOMBRE3_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(n3_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(151, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOMBRE1_label))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMBRE2_label)
                    .addComponent(n2_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n3_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOMBRE3_label))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMBRE4_label)
                    .addComponent(n4_cuadrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anidir_boton)
                    .addComponent(eliminar_boton)
                    .addComponent(aceptar_boton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_botonActionPerformed
        if (nplayers > 1){
            nplayers--;
            names_fields.get(nplayers).setVisible(false);
            names_labels.get(nplayers).setVisible(false);
        }
    }//GEN-LAST:event_eliminar_botonActionPerformed

    private void n1_cuadrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_cuadrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1_cuadrotxtActionPerformed

    private void aceptar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_botonActionPerformed
        for (int i = 0; i < nplayers; i++)
            names.add(names_fields.get(i).getText());
        dispose();
    }//GEN-LAST:event_aceptar_botonActionPerformed

    private void n2_cuadrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2_cuadrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2_cuadrotxtActionPerformed

    private void n3_cuadrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3_cuadrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3_cuadrotxtActionPerformed

    private void n4_cuadrotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4_cuadrotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n4_cuadrotxtActionPerformed

    private void anidir_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anidir_botonActionPerformed
        if (nplayers < 4){
            names_fields.get(nplayers).setVisible(true);
            names_labels.get(nplayers).setVisible(true);
            nplayers++;
        }
    }//GEN-LAST:event_anidir_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NamesCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NamesCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NamesCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NamesCapture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NamesCapture dialog = new NamesCapture(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOMBRE1_label;
    private javax.swing.JLabel NOMBRE2_label;
    private javax.swing.JLabel NOMBRE3_label;
    private javax.swing.JLabel NOMBRE4_label;
    private javax.swing.JButton aceptar_boton;
    private javax.swing.JButton anidir_boton;
    private javax.swing.JButton eliminar_boton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField n1_cuadrotxt;
    private javax.swing.JTextField n2_cuadrotxt;
    private javax.swing.JTextField n3_cuadrotxt;
    private javax.swing.JTextField n4_cuadrotxt;
    // End of variables declaration//GEN-END:variables
}
