/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.ShieldToUI;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author pedrojgl
 */
public class ShieldView extends javax.swing.JPanel implements CombatElementView{
    private boolean selected;
    
    /**
     * Creates new form ShieldView
     */
    public ShieldView() {
        initComponents();
        selected = false;
    }
    
    @Override
    public boolean isSelected(){
        return selected;
    }
    
    public void setShieldView(ShieldToUI shieldui){
        if  (shieldui == null){
            setVisible(false);
        } else {
            boost_label.setText(String.valueOf(shieldui.getBoost()));
            nuses_label.setText(String.valueOf(shieldui.getUses()));
            
            this.setOpaque(false);
            this.setBackground(Color.green);
            
            repaint();
            revalidate();
            
            setVisible(true);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        potencia_label = new javax.swing.JLabel();
        usos_label = new javax.swing.JLabel();
        ESCUDO_label = new javax.swing.JLabel();
        boost_label = new javax.swing.JLabel();
        nuses_label = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        potencia_label.setText("Potencia:");

        usos_label.setText("Usos:");

        ESCUDO_label.setText("ESCUDO");

        boost_label.setText("jLabel4");

        nuses_label.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ESCUDO_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potencia_label)
                            .addComponent(usos_label))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boost_label)
                            .addComponent(nuses_label))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ESCUDO_label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potencia_label)
                    .addComponent(boost_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usos_label)
                    .addComponent(nuses_label))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        this.setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ESCUDO_label;
    private javax.swing.JLabel boost_label;
    private javax.swing.JLabel nuses_label;
    private javax.swing.JLabel potencia_label;
    private javax.swing.JLabel usos_label;
    // End of variables declaration//GEN-END:variables

}
