/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.WeaponToUI;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author pedrojgl
 */
public class WeaponView extends javax.swing.JPanel implements CombatElementView {
    private boolean selected;
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents();
        selected = false;
    }
    
    @Override
    public boolean isSelected(){
        return selected;
    }
    
    public void setWeaponView(WeaponToUI weaponui){
        if(weaponui == null){
            setVisible(false);
        }else{
            power_label.setText(String.valueOf(weaponui.getPower()));
            nuses_label.setText(String.valueOf(weaponui.getUses())); 
            weapType_label.setText(weaponui.getType().toString());
            
            this.setOpaque(false);
            this.setBackground(Color.green);
            
            repaint();
            revalidate();
            
            setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo_label = new javax.swing.JLabel();
        potencia_label = new javax.swing.JLabel();
        usos_label = new javax.swing.JLabel();
        weapType_label = new javax.swing.JLabel();
        power_label = new javax.swing.JLabel();
        nuses_label = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tipo_label.setText("Tipo:");

        potencia_label.setText("Potencia:");

        usos_label.setText("Usos:");

        weapType_label.setText("jLabel4");

        power_label.setText("jLabel5");

        nuses_label.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usos_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuses_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(potencia_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(power_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tipo_label)
                        .addGap(70, 70, 70)
                        .addComponent(weapType_label)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_label)
                    .addComponent(weapType_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potencia_label)
                    .addComponent(power_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usos_label)
                    .addComponent(nuses_label))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        this.setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nuses_label;
    private javax.swing.JLabel potencia_label;
    private javax.swing.JLabel power_label;
    private javax.swing.JLabel tipo_label;
    private javax.swing.JLabel usos_label;
    private javax.swing.JLabel weapType_label;
    // End of variables declaration//GEN-END:variables

}
